#!/bin/sh

set -ex

#cp init-lysstyring.conf /etc/init/lysstyring.conf

cp initd-lys /etc/init.d/lys
chmod +x /etc/init.d/lys
update-rc.d lys defaults

cp lys /usr/local/bin/lys

pydest=/usr/local/lib/python2.7/dist-packages/lysstyring
rm -rf $pydest
mkdir -p $pydest
cp -av *.py $pydest/
( cd $pydest/ && python -m compileall . )
