#!/bin/bash
# /etc/init.d/lys

### BEGIN INIT INFO
# Provides:          lys
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used to manage lysstyring
### END INIT INFO

. /lib/lsb/init-functions

case "$1" in 
    start)
        log_daemon_msg "Starting lysstyring" "lys" || true
        if start-stop-daemon --start --quiet --oknodo --make-pidfile --pidfile /var/run/lys.pid --background --exec /usr/local/bin/lys -- ; then
            log_end_msg 0 || true
        else
            log_end_msg 1 || true
        fi
        ;;
    stop)
        log_daemon_msg "Stopping lysstyring" "lys" || true
        if start-stop-daemon --stop --quiet --oknodo --pidfile /var/run/lys.pid; then
            log_end_msg 0 || true
        else
            log_end_msg 1 || true
        fi
        ;;
    *)
        echo "Usage: /etc/init.d/lysstyring start|stop"
        exit 1
        ;;
esac

exit 0

