#!/usr/bin/env python
# -*-python-*-
import os,sys
import lumina.main as lumina
from twisted.python import log
from twisted.internet import reactor
if os.name != 'nt':
    from twisted.python import syslog
import argparse

ap = argparse.ArgumentParser()
ap.add_argument('--daemon', action='store_true', help='Daemonize application')
ap.add_argument('--pidfile', default='/var/run/lumid.pid', metavar='FILENAME', help='Set the pidfile')
if os.name != 'nt':
    ap.add_argument('--syslog', action='store_true', default=False, help='Enable syslog logging')
ap.add_argument('-c', '--config', default=None, metavar='CONFIG', help='Read configuration file')


opts = ap.parse_args()

# Read configuration file
config = lumina.readconfig(opts.config)

# Daemonize
if opts.daemon:
    lumina.daemonize(pidfile=opts.pidfile)
    opts.syslog=True

# Start logging
if os.name != 'nt' and opts.syslog:
    syslog.startLogging(prefix='Lumina')
else:
    log.startLogging(sys.stdout)

# Start main app
lumina.main(config)

# Start twisted
log.msg('Server PID: %s' %(os.getpid()), system='-')
reactor.run()
