#!/usr/bin/env python
# -*-python-*-
import os,sys
from lumina.main import daemonize,controller,client_lys
from twisted.python import log, syslog
from twisted.internet import reactor
import argparse

ap = argparse.ArgumentParser()
ap.add_argument('--daemon', action='store_true', help='Daemonize application')
ap.add_argument('--pidfile', default='/var/run/lumina', metavar='FILENAME', help='Set the pidfile')
ap.add_argument('--syslog', action='store_true', default=False, help='Enable syslog logging')
ap.add_argument('--webroot', default='/usr/share/lumina/www', metavar='PATH', help='Set the html server path')
ap.add_argument('--webport', default='80', metavar='PORT', help='Set the port to run the html server')

opts = ap.parse_args()
if opts.daemon:
    daemonize(pidfile=opts.pidfile)

if opts.syslog:
    syslog.startLogging(prefix='Lumina')
else:
    log.startLogging(sys.stdout)

# Start main controller(s)
controller(webroot=opts.webroot, webport=int(opts.webport))
client_lys()

# Start twisted
log.msg('Server PID: %s' %(os.getpid()), system='-')
reactor.run()
