FROM ubuntu:16.04
MAINTAINER Svein Seldal <sveinse@seldal.com>

ENV DEBIAN_FRONTEND=noninteractive
ENV USER_UID=${UID}
ENV USER_GID=${GID}
ENV BROOT=1

COPY setup-xenial /tmp/setup-xenial
RUN /tmp/setup-xenial
