FROM scratch
MAINTAINER Svein Seldal <sveinse@seldal.com>

ADD rootfs/ /

ENV \
    DEBIAN_FRONTEND=noninteractive \
    USER_UID=${UID} \
    USER_GID=${GID} \
    BROOT=1

RUN /tmp/prepare-xu

CMD ["/bin/bash"]
