FROM ubuntu:16.04
MAINTAINER Svein Seldal <sveinse@seldal.com>

ENV \
    DEBIAN_FRONTEND=noninteractive \
    USER_UID=${UID} \
    USER_GID=${GID} \
    BROOT=1

COPY prepare-xenial /tmp/prepare-xenial

RUN /tmp/prepare-xenial
