#!/bin/bash -ex
# Target setup-tools for Raspbian

# Ensure no services will try to affect the host machine, so override all such tools
#for fn in \
#    /usr/sbin/invoke-rc.d \
#    /sbin/start \
#    /sbin/poweroff \
#    /sbin/reboot \
#    /sbin/initctl \
#    /sbin/telinit \
#    ; do
#    dpkg-divert --add --local --divert ${fn}.install --rename ${fn}
#    cp /bin/true ${fn}
#done

cat >/etc/apt/apt.conf.d/99_norecommends <<EOF
APT {
	Install-Recommends "0";
	Install-Suggests "0";
	Get {
		AllowUnauthenticated "1";
	};
};
EOF

chmod 4755 /usr/bin/sudo

dpkg -P \
	raspberrypi-sys-mods \
        raspberrypi-kernel \
        raspberrypi-bootloader \
        libraspberrypi0 \
        libraspberrypi-bin \
        libraspberrypi-dev \
        libraspberrypi-doc \
        firmware-atheros \
        firmware-brcm80211 \
        firmware-libertas \
        firmware-ralink \
        firmware-realtek

# Update installation
apt-get update
apt-get dist-upgrade -y
apt-get install -y \
        build-essential \
        debhelper \
        fakeroot
apt-get clean
