#!/bin/bash -ex
# Target setup-tools for XU

# Ensure no services will try to affect the host machine, so override all such tools
#for fn in \
#    /usr/sbin/invoke-rc.d \
#    /sbin/start \
#    /sbin/poweroff \
#    /sbin/reboot \
#    /sbin/initctl \
#    /sbin/telinit \
#    ; do
#    dpkg-divert --add --local --divert ${fn}.install --rename ${fn}
#    cp /bin/true ${fn}
#done

addgroup --gid ${USER_GID} build
adduser --uid ${USER_UID} --gid ${USER_GID} --shell /bin/bash --gecos "Build User" --disabled-password build

cat >/etc/apt/apt.conf.d/99_norecommends <<EOF
APT {
	Install-Recommends "0";
	Install-Suggests "0";
	Get {
		AllowUnauthenticated "1";
	};
};
EOF

cat >/etc/apt/sources.list <<EOF
deb http://ports.ubuntu.com/ubuntu-ports xenial main universe multiverse restricted
deb http://ports.ubuntu.com/ubuntu-ports xenial-updates main universe multiverse restricted
deb http://ports.ubuntu.com/ubuntu-ports xenial-security main universe multiverse restricted
deb http://ports.ubuntu.com/ubuntu-ports xenial-backports main universe multiverse restricted
EOF

# Update installation
apt-get update
apt-get dist-upgrade -y
apt-get install -y \
    build-essential \
    debhelper \
    fakeroot \
    sudo \
    \
    python \
    dh-python \
    python-setuptools
apt-get clean

cat >>/etc/sudoers <<EOF
build ALL=(ALL) NOPASSWD: ALL
EOF
