#!/bin/bash -ex
# Target setup-tools for Raspbian

cat >/etc/apt/apt.conf.d/99_norecommends <<EOF
APT {
	Install-Recommends "0";
	Install-Suggests "0";
	Get {
		AllowUnauthenticated "1";
	};
};
EOF

chmod 4755 /usr/bin/sudo

dpkg -P \
    raspberrypi-sys-mods \
    raspberrypi-kernel \
    raspberrypi-bootloader \
    libraspberrypi0 \
    libraspberrypi-bin \
    libraspberrypi-dev \
    libraspberrypi-doc \
    firmware-atheros \
    firmware-brcm80211 \
    firmware-libertas \
    firmware-ralink \
    firmware-realtek

# Update installation
apt-get update
apt-get dist-upgrade -y
apt-get install -y \
    build-essential \
    debhelper \
    fakeroot \
    \
    python \
    dh-python \
    python-setuptools
apt-get clean
