#!/bin/sh -ex

sudo cp contrib/deploy/tellstick.conf /etc/tellstick.conf
sudo service telldusd restart

sudo mkdir -p /etc/lumina/
sudo cp contrib/deploy/lum3.json /etc/lumina/lumina.json
sudo service lumina restart
