#!/bin/sh -ex

# In advance the Docker has been setup using:
#
# docker volume create lumina
# docker network create webbride

version="$(cat lumina/__init__.py | sed -n "s/__version__\s*=\s*'\(.*\)'/\1/p")"

case "$1" in
    install)
        sudo docker stop lumina || true
        sudo docker rm lumina || true
        sudo docker run -d --name lumina \
            --network webbridge \
            -p 8326:8326 -p 5326:5326 \
            --hostname lys \
            -vlumina:/etc/lumina \
            lumina:$version
        ;;

    deploy)
        sudo cp contrib/deploy/lys.json /var/lib/docker/volumes/lumina/_data/lumina.json
        sudo docker restart lumina
        ;;

    *)
        echo "$0: Unknown deploy op '$1'"
        exit 1
        ;;
esac
