#!/bin/bash -ex
# Target prepare-tools for Raspbian

cat >/etc/apt/apt.conf.d/99_norecommends <<EOF
APT {
	Install-Recommends "0";
	Install-Suggests "0";
	Get {
		AllowUnauthenticated "1";
	};
};
EOF

# Update installation
apt update
#apt dist-upgrade -y
apt install -y \
    build-essential \
    debhelper \
    dh-python \
    dh-systemd \
    fakeroot \
    wget \
    python-setuptools \
    python3-setuptools \
    python-all \
    python3-all

apt autoremove -y
apt clean
