#!/bin/bash

ME="$(basename "$0")"

# To fetch the source file
#wget -O ola_$V.orig.tar.gz https://github.com/OpenLightingProject/ola/releases/download/$V/ola-$V.tar.gz

V=0.10.2
S=ola_$V-1sveinse1.dsc
D=ola-$V
bdir=

# -------------------------------------------------------------------------

# -- Print usage
usage () {
    cat <<EOF
$ME --
(C) 2016 Svein Seldal <sveinse@seldal.com>

Usage: $ME [OPTION]

Options:
  -b DIR, --build DIR  Build in DIR
  -h, --help           Print this help
EOF
}

# -- Parse arguments
args=()
while [[ "$#" -gt 0 ]]
do
    case "$1" in
        -h|--help)
            usage
            exit 1
            ;;
        -b|--build)
            bdir="$2"
            shift
            ;;
        --)
            shift
            break
            ;;
        -*)
            echo "$ME: Invalid option '$1'"
            exit 1
            ;;
        *)
            args+=("$1")
            ;;
    esac
    shift
done

# Catch up any args after -- as well
while [[ "$#" -gt 0 ]]; do
    args+=("$1")
    shift
done

# -------------------------------------------------------------------------

# Get Build-Depends and list of Files from .dsc file (given by $S)
files=("$S")
while IFS='' read -r l; do
    case "$l" in
        'Build-Depends:'*)
            bdep="${l##Build-Depends: }"
            build_deps="$(echo "$bdep" | sed -e 's/ *\(([^)]*)\)*, */ /g')"
            ;;
        Files:)
            in_files=1
            ;;
        ' '*)
            if [[ "$in_files" ]]; then
                file="${l##* }"
                files+=("$file")
            fi
            ;;
        *)
            in_files=
            ;;
    esac
done <$S

# -------------------------------------------------------------------------

# Create build dir and symlink the sources from it
if [[ "$bdir" ]]; then
    echo "$ME: Setting up build in $bdir"
    mkdir -p "$bdir"
    src="$PWD"
    cd "$bdir"
    for f in "${files[@]}"; do
        rm -f "$f"
        ln -s "$src/$f" "$f"
    done
fi

set -ex

# Build depends (for Docker instances)
if [[ "$BROOT" ]]; then
    sudo apt install -y $build_deps
fi

# Do the build
rm -rf $D
dpkg-source -x $S $D
cd $D
dpkg-buildpackage -b -uc -us "${args[@]}"
